# Site settings
version: 2.1
title: 'Fernseed'
url: 'http://fernseed.org'
history_url: 'https://github.com/fernseed/fernseed.github.io/commits/master/'
feed_url: 'http://feeds.feedburner.com/fernseed'
description: 'Weird fiction, weird technology &amp; weird thinking.'
standards: 'HTML5, CSS3'
timezone: 'Europe/Belfast'
permalink: /:categories/:title/
reading_wpm: 180
paginate: 10
paginate_path: "/archive/:num/"

# Writing stats
writing:
  goal: 500

# Contact information
twitter:
  username: 'dmcgk'

contact:
  name: 'Darren McGuicken'
  twitter: '@dmcgk'
  github: '@dmcgk'
  email: 'feedback@fernseed.org'
  location: 'Northern Ireland, UK'

social:
  type: 'person'
  name: 'Darren McGuicken'
  links: ["http://twitter.com/dmcgk"]

# Non-article collections
collections:
  - gallery

# Build settings
environment: production
markdown: kramdown
highlighter: rouge
exclude: [vendor]
sass:
  sass_dir: _sass
  style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "errors"
    values:
      layout: "index"
      sitemap: false

# Plugins
gems:
## GitHub Pages compatible
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate

# Plugin settings
jekyll-mentions:
  base_url: 'https://twitter.com'
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: all
kramdown:
  auto_ids: true
  toc_levels: 1..6
