# Site settings
version: 2.1
title: 'fernseed'
url: 'http://fernseed.org'
history_url: 'https://github.com/fernseed/fernseed.github.io/commits/master/'
feed_url: 'http://feeds.feedburner.com/fernseed'
description: 'Weird fiction, weird technology & weird thinking.'
standards: 'HTML5, CSS3'
timezone: 'Europe/Belfast'
permalink: /:categories/:title/
reading_wpm: 180

# Site contact information
contact:
    name: 'Darren McGuicken'
    twitter: '@dmcgk'
    github: '@dmcgk'
    email: 'feedback@fernseed.org'
    location: 'Northern Ireland, UK'

# Build settings
environment: production
markdown: kramdown
highlighter: pygments
exclude: [vendor]
sass:
    sass_dir: _sass
    style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "errors"
    values:
      layout: "index"
      sitemap: false

# Plugins
gems:
## GitHub Pages compatible
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
## Others

# Plugin settings
jekyll-mentions:
    base_url: 'https://twitter.com'
compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
kramdown:
  auto_ids: true
  toc_levels: 1..6
